version: '3'

services:
  # PostgreSQL database on port 7001
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sabir
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main_db
    ports:
      - "7001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB database on port 7002
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: sabir
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "7002:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis cache on port 7003
  redis:
    image: redis:latest
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "7003:6379"
    volumes:
      - redis_data:/data

  # Adminer database management on port 8001
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8001:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
