version: '3'

services:
  nodejs:
    image: node:20.5.0
    container_name: nodejs-dev
    working_dir: /app
    volumes:
      - ../../Projects:/app
      - nodejs_modules:/app/node_modules
    ports:
      # Web development ports
      - "5001:5001"  # Next.js
      - "5002:5002"  # serve
      - "5003:5003"  # WordPress
      - "5004:5004"  # Shopify
      # Application ports
      - "6001:6001"  # Express API
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # Keep container running
    
  nodejs-tools:
    image: node:20.5.0
    container_name: nodejs-tools
    working_dir: /tools
    volumes:
      - ../../Tools:/tools
      - nodejs_tools_modules:/tools/node_modules
    ports:
      # Development tools ports
      - "9001-9010:8001-8010"
    environment:
      - NODE_ENV=development
    command: tail -f /dev/null  # Keep container running

volumes:
  nodejs_modules:
  nodejs_tools_modules:
