services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "4728:4728"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sabir
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: sabir_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
